### ISSUE TITLE
Craft 3 upgrade?

### ISSUE THREAD

**Issue by ghost** [aelvan/VarnishPurge-Craft#20]
@aelvan do you intend on upgrading this plugin to Craft 3 in the near future? If not would you mind if I make the necessary changes and create a Pull Request?

**Comment by aelvan** [comment]
No, I'm not planning on updating it. Feel free to fork/copy the code and make a Craft version, the code is MIT, so no problem. Got a similar request from @njpanderson som time ago, he's working on something here: https://github.com/njpanderson/Citrus

**Comment by aelvan** [comment]
Aand, there is also Upper which uses XKEY for clearing caches based on tags, that looks pretty smooth. https://github.com/ostark/upper
